### ISSUE TITLE
Is project based learning still alive?

### ISSUE THREAD

**Issue by bobeff** [practical-tutorials/project-based-learning#295]
The last commit is from August 23, 2020. Currently, there are 86 pending pull requests. Is the project still alive? If the author is no longer interested to maintain it or he does not have enough time maybe it is a good idea to transfer the project to an independent organization where to be maintained by the community.

**Comment by bliotti** [comment]
Go blockchain series now at https://jeiwan.net/posts/building-blockchain-in-go-part-1/

**Comment by enkeyz** [comment]
There would be many people, who would like to be maintainers. Is there any chance for this?

**Comment by enkeyz** [comment]
So after I tried to communicate with @tuvtran and got now answer, I created a fork and an organization for the sole purpose of it to continuously maintain this project. You can see the issue here: https://github.com/tuvtran/project-based-learning/issues/309

**Comment by iamleomoko** [comment]
> Hi, thanks for raising this. I've been busy with my day job and some personal issues so really haven't had any time for this yet... However, in the upcoming months I'll be available again and I plan to do a grooming of opening issues/PRs sometime in the next 2 weeks.

I hope you have everything sorted out hey
