### ISSUE TITLE
New projectbasedlearning fork looking for maintainers

### ISSUE THREAD

**Issue by enkeyz** [practical-tutorials/project-based-learning#309]
Hello guys!

I'm finally decided to fork this and create an organization, so the whole community can benefit from the continuous development of this project.

If you'd like to contribute, please head to https://github.com/Learning-by-Doing-it/project-based-learning/issues/1 and make a comment. (Not mandatory, you can just sent PRs.)

Also would like to thank @tuvtran for his hard work since he opened this repo.

Thank you,

Norbert Klar

**Comment by tuvtran** [comment]
Hi @enkeyz, thanks for raising this. IMHO, opening a fork works too but since this repo has a lot of outstanding PRs and issues, let's keep everything here. I'll open a thread to look for maintainers and I assume you're interested in being one too.

**Comment by tuvtran** [comment]
@enkeyz I posted an update here https://github.com/tuvtran/project-based-learning/issues/310
