### ISSUE TITLE
need a script to search for identical files by content on the cpp

### ISSUE THREAD

**Issue by KhondamirN** [practical-tutorials/project-based-learning#340]

**Comment by KhondamirN** [comment]
help pls

**Comment by Ronkiro** [comment]
This isn't the best place for this, but you can find it by Googling a bit. This repo is for learning by doing

**Comment by KhondamirN** [comment]
Thank you
--
Отправлено из Mail.ru для Android четверг, 27 января 2022г., 18:42 +03:00 от Alexander Santos  ***@***.*** :
