### ISSUE TITLE
JavaScript TDD Todo List App

### ISSUE THREAD

**Issue by ghost** [practical-tutorials/project-based-learning#342]
A step-by-step complete beginner example/tutorial for building a Todo List App (TodoMVC) from scratch in JavaScript following Test Driven Development (TDD) best practice.
https://github.com/dwyl/javascript-todo-list-tutorial

**Comment by Krish-bhardwaj** [comment]
Hi i am a fresher looking for some opensource contribution can u help me out i want to contribute to your project and can u assign me this issue:)

**Comment by enkeyz** [comment]
> Hi i am a fresher looking for some opensource contribution can u help me out i want to contribute to your project and can u assign me this issue:)

Just make a PR.

**Comment by Krish-bhardwaj** [comment]
> > Hi i am a fresher looking for some opensource contribution can u help me out i want to contribute to your project and can u assign me this issue:)
> 
> Just make a PR.

So basically i need to make a  repo like https://github.com/dwyl/javascript-todo-list-tutorial which has complete tutorial and explanation on how to make a todo list using JavaScript

**Comment by enkeyz** [comment]
> > > Hi i am a fresher looking for some opensource contribution can u help me out i want to contribute to your project and can u assign me this issue:)
> > 
> > 
> > Just make a PR.
> 
> So basically i need to make a repo like https://github.com/dwyl/javascript-todo-list-tutorial this which has complete tutorial and explanation on how to make a todo list using JavaScript

https://github.com/firstcontributions/first-contributions

**Comment by Krish-bhardwaj** [comment]
@enkeyz  i have opened a PR please check it
