### ISSUE TITLE
About adding game development projects with game engines(Unity, Unreal..)

### ISSUE THREAD

**Issue by mathew4STAR** [practical-tutorials/project-based-learning#350]
I am not sure whether this falls in line with what this list is trying to achieve, but would it be a good to add **Unity** projects under **C#** and **Unreal** Projects under **C++**?
If it is not, please close this issue. 

I think game development would be great place to start to learn programming.

If it is fine then I could try to build a short list for game development.

Thank you.

**Comment by enkeyz** [comment]
This project mostly focused on material that you can't find with a simple search. You can find Unreal/Unity tutorials with a simple search. Closing.
