### ISSUE TITLE
Broken/Dead Links (Go): Build Web Application with GoLang

### ISSUE THREAD

**Issue by AxzelBC** [practical-tutorials/project-based-learning#412]
## Expected Behavior
Clicking on the link should take you to a website with content.

## Current Behavior
The links currently go to a page that says, "401 Unauthorized".

## Possible Solution
Remove or update the links. Preferably update, but remove to avoid confusion.

## Steps to Reproduce
Click on the link above.

**Comment by enkeyz** [comment]
Works for me.
